config/routes.rb
Rails.application.routes.draw do

  resources :rooms

  get 'home/index'
  get 'home/room'

  devise_for :user
  resources :countries, :cities, :addrs, :roles, :users, :ui_presets

  get '/groups', to: 'users#by_role', defaults: { role: 'group' }

  get '/random-pass', to: 'home#random_password', format: :json
  root to: 'home#index'
  

end

app/models/addr.rb
class Addr < ActiveRecord::Base
  belongs_to :city, inverse_of: :addrs
  delegate :country, to: :city
  has_one :user, inverse_of: :addr
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country, inverse_of: :cities
  has_many :addrs, inverse_of: :city
  has_many :users, through: :addrs
end

app/models/city_name.rb
class CityName < ActiveRecord::Base
  belongs_to :city
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities, inverse_of: :country
  
  def inhabitants
    self.cities.users
  end

end

app/models/country_name.rb
class CountryName < ActiveRecord::Base
  belongs_to :country
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, inverse_of: :role
  validates :name, presence: true, uniqueness: true
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :room
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  validates :title, :body, presence: true
  after_validation :make_html_cache

  private
  def make_html_cache
    md = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, highlight: true, underline: true, lax_spacing: true, autolink: true, fenced_code_blocks: true, tables: true, no_intra_emphasis: true)
    self.html_cache = md.render(self.body)
  end
end

app/models/ui_preset.rb
class UiPreset < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :name, :attrs, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable, :lockable, :timeoutable
  belongs_to :addr, inverse_of: :user
  belongs_to :role, inverse_of: :users
  has_and_belongs_to_many :ui_presets
  
  validates :name, :role_id, :email, presence: true
  validates :name, :email, uniqueness: true
  validates :role_id, inclusion: { in: Role.first.id .. Role.last.id }

  def man?
    self.sex
  end
  def woman?
    ! self.sex
  end
  
  def role_is?(name)
    self.role.name == name
  end
  def method_missing(metoda, *args, &block)
    logger.debug "User.method_missing: '#{metoda}'"
    if metoda.to_s =~ /^(#{Role.all.pluck(:name).join('|')})\?$/
      role_is?($1)
    else
      super
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless current_user.admin?
      redirect_to controller: 'home', action: 'room'
    end
    rooms = Room.all.order(:name)
    groups = User.joins(:role).where("roles.name = 'group'").order('roles.name')
  end

  def room
    rooms = Room.all.order(:name)
  end

  def random_password
    pass = ''
    sep = [' ', '', '-', '_', '/', '*']
    words = File.readlines('lib/vocabulary')
    words.sample(10).each do |w|
      pass += char_shuffle(w.chomp) + sep[rand(sep.count-1)] if w.size > 3
      break if pass.size > 10
    end
    unless pass =~ /[0-9]/
      pass[rand(pass.size-1)] = rand(10).to_s
    end
    render json: { pass: pass }
  end

  private
  def char_shuffle(w)
    w = w[0] + w[1..-2].split(//).shuffle.join('') + w[-1]
    w[-1] = w[-1].upcase if rand(10) > 4
    w.gsub!(/i/i, '1') if rand(10) > 4
    w.gsub!(/o/i, '0') if rand(10) > 4
    w.size.times do |i|
      w[i] = w[i].swapcase if rand(10) > 4
    end
    return w
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_filter :check_permissions

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all.order(:name).includes(:users)
    respond_to do |format|
      format.html
      format.json { render :index, layout: false }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end
    def role_params
      params.require(:role).permit(:name)
    end
    # disable all except admins
    def check_permissions
      unless current_user.admin?#  && action_name =~ /^(new|edit|destroy|update|create)$/
        redirect_to :root
      end
    end
end

app/helpers/addrs_helper.rb
module AddrsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/ui_presets_helper.rb
module UiPresetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/roles/_form.haml
= form_for(@role) do |f|
  - if @role.errors.any?
    #error_explanation
      %h2
        = pluralize(@role.errors.count, "error")
        prohibited this role from being saved:
      %ul
        - @role.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/roles/edit.haml
%h1 Editing role
= render 'form'
= link_to 'Show', @role
|
\#{link_to 'Back', roles_path}

app/views/roles/index.haml
%h1.h1 Listing roles
.row
  .col-md-12
    %table.table.table-stripped
      %thead
        %tr
          %th= t('role.name')
          %th= t('users')
          %th
      %tbody
        - @roles.each do |role|
          %tr
            %td=link_to role.name, role
            %td=role.users.count
            %td
              =link_to t('role.edit'), edit_role_path(role)
              |
              =link_to t('role.destroy'), role, method: :delete, data: { confirm: "Delete the role #{role.name}?" }
    %br/
    =link_to t('role.new'), new_role_path, class: 'btn btn-success'

app/views/roles/new.haml
%h1 New role
= render 'form'
= link_to 'Back', roles_path

app/views/roles/show.haml
%p#notice= notice
.row
  .col-md-12
    Role:
    %strong= @role.name
    %table.table
      %tr
        %th name, email
        %th created@
        %th session@
        %th ip
      - @role.users.each do |user|
        %tr
          %td
            =user.name
            =user.email
          %td=user.created_at
          %td=user.current_sign_in_at
          %td=user.current_sign_in_ip

    .btn-group
      =link_to :edit, edit_role_path(@role), class: 'btn btn-info'
      =link_to :back, roles_path, class: 'btn btn-success'