config/routes.rb
Rails.application.routes.draw do

  resources :rooms

  get 'home/index'
  get 'home/room'

  devise_for :user
  resources :countries, :cities, :addrs, :roles, :users, :ui_presets

  get '/groups', to: 'users#by_role', defaults: { role: 'group' }

  get '/random-pass', to: 'home#random_password', format: :json
  root to: 'home#index'
  

end

app/models/addr.rb
class Addr < ActiveRecord::Base
  belongs_to :city, inverse_of: :addrs
  delegate :country, to: :city
  has_one :user, inverse_of: :addr
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country, inverse_of: :cities
  has_many :addrs, inverse_of: :city
  has_many :users, through: :addrs
end

app/models/city_name.rb
class CityName < ActiveRecord::Base
  belongs_to :city
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities, inverse_of: :country
  
  def inhabitants
    self.cities.users
  end

end

app/models/country_name.rb
class CountryName < ActiveRecord::Base
  belongs_to :country
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, inverse_of: :role
  validates :name, presence: true, uniqueness: true
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :room
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  validates :title, :body, presence: true
  after_validation :make_html_cache

  private
  def make_html_cache
    md = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, highlight: true, underline: true, lax_spacing: true, autolink: true, fenced_code_blocks: true, tables: true, no_intra_emphasis: true)
    self.html_cache = md.render(self.body)
  end
end

app/models/ui_preset.rb
class UiPreset < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :name, :attrs, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable, :lockable, :timeoutable
  belongs_to :addr, inverse_of: :user
  belongs_to :role, inverse_of: :users
  has_and_belongs_to_many :ui_presets
  
  validates :name, :role_id, :email, presence: true
  validates :name, :email, uniqueness: true
  validates :role_id, inclusion: { in: Role.first.id .. Role.last.id }

  def man?
    self.sex
  end
  def woman?
    ! self.sex
  end
  
  def role_is?(name)
    self.role.name == name
  end
  def method_missing(metoda, *args, &block)
    logger.debug "User.method_missing: '#{metoda}'"
    if metoda.to_s =~ /^(#{Role.all.pluck(:name).join('|')})\?$/
      role_is?($1)
    else
      super
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  before_filter :check_permissions

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_city
      @city = City.find(params[:id])
    end
    def city_params
      params.require(:city).permit(:name, :country_id)
    end
    def check_permissions
      # fish
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless current_user.admin?
      redirect_to controller: 'home', action: 'room'
    end
    rooms = Room.all.order(:name)
    groups = User.joins(:role).where("roles.name = 'group'").order('roles.name')
  end

  def room
    rooms = Room.all.order(:name)
  end

  def random_password
    pass = ''
    sep = [' ', '', '-', '_', '/', '*']
    words = File.readlines('lib/vocabulary')
    words.sample(10).each do |w|
      pass += char_shuffle(w.chomp) + sep[rand(sep.count-1)] if w.size > 3
      break if pass.size > 10
    end
    unless pass =~ /[0-9]/
      pass[rand(pass.size-1)] = rand(10).to_s
    end
    render json: { pass: pass }
  end

  private
  def char_shuffle(w)
    w = w[0] + w[1..-2].split(//).shuffle.join('') + w[-1]
    w[-1] = w[-1].upcase if rand(10) > 4
    w.gsub!(/i/i, '1') if rand(10) > 4
    w.gsub!(/o/i, '0') if rand(10) > 4
    w.size.times do |i|
      w[i] = w[i].swapcase if rand(10) > 4
    end
    return w
  end
end

app/helpers/addrs_helper.rb
module AddrsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/ui_presets_helper.rb
module UiPresetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
    <%= f.text_field :country_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.country %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @city.country %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>