config/routes.rb
Rails.application.routes.draw do

  resources :rooms

  get 'home/index'
  get 'home/room'

  devise_for :user
  resources :countries, :cities, :addrs, :roles, :users, :ui_presets

  get '/groups', to: 'users#by_role', defaults: { role: 'group' }

  get '/random-pass', to: 'home#random_password', format: :json
  root to: 'home#index'
  

end

app/models/addr.rb
class Addr < ActiveRecord::Base
  belongs_to :city, inverse_of: :addrs
  delegate :country, to: :city
  has_one :user, inverse_of: :addr
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country, inverse_of: :cities
  has_many :addrs, inverse_of: :city
  has_many :users, through: :addrs
end

app/models/city_name.rb
class CityName < ActiveRecord::Base
  belongs_to :city
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities, inverse_of: :country
  
  def inhabitants
    self.cities.users
  end

end

app/models/country_name.rb
class CountryName < ActiveRecord::Base
  belongs_to :country
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, inverse_of: :role
  validates :name, presence: true, uniqueness: true
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :room
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  validates :title, :body, presence: true
  after_validation :make_html_cache

  private
  def make_html_cache
    md = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, highlight: true, underline: true, lax_spacing: true, autolink: true, fenced_code_blocks: true, tables: true, no_intra_emphasis: true)
    self.html_cache = md.render(self.body)
  end
end

app/models/ui_preset.rb
class UiPreset < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :name, :attrs, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable, :lockable, :timeoutable
  belongs_to :addr, inverse_of: :user
  belongs_to :role, inverse_of: :users
  has_and_belongs_to_many :ui_presets
  
  validates :name, :role_id, :email, presence: true
  validates :name, :email, uniqueness: true
  validates :role_id, inclusion: { in: Role.first.id .. Role.last.id }

  def man?
    self.sex
  end
  def woman?
    ! self.sex
  end
  
  def role_is?(name)
    self.role.name == name
  end
  def method_missing(metoda, *args, &block)
    logger.debug "User.method_missing: '#{metoda}'"
    if metoda.to_s =~ /^(#{Role.all.pluck(:name).join('|')})\?$/
      role_is?($1)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  # before_filter :set_applocale

private
  def set_applocale
    lang = :ru
    # checking url
    if request.params[:ispeak] && request.params[:ispeak] =~ /^\w\w$/
      logger.debug "User asks for #{request.params[:ispeak]} language"
      lang = request.params[:ispeak]
    # checking cookies
    elsif 
      lang = cookies[:ispeak]
    # checking browser
    else
      ihave = %w(ru he de en)
      http_accept_language.compatible_language_from(ihave)
    end
    I18n.locale = lang
    cookies[:ispeak] = lang
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless current_user.admin?
      redirect_to controller: 'home', action: 'room'
    end
    rooms = Room.all.order(:name)
    groups = User.joins(:role).where("roles.name = 'group'").order('roles.name')
  end

  def room
    rooms = Room.all.order(:name)
  end

  def random_password
    pass = ''
    sep = [' ', '', '-', '_', '/', '*']
    words = File.readlines('lib/vocabulary')
    words.sample(10).each do |w|
      pass += char_shuffle(w.chomp) + sep[rand(sep.count-1)] if w.size > 3
      break if pass.size > 10
    end
    unless pass =~ /[0-9]/
      pass[rand(pass.size-1)] = rand(10).to_s
    end
    render json: { pass: pass }
  end

  private
  def char_shuffle(w)
    w = w[0] + w[1..-2].split(//).shuffle.join('') + w[-1]
    w[-1] = w[-1].upcase if rand(10) > 4
    w.gsub!(/i/i, '1') if rand(10) > 4
    w.gsub!(/o/i, '0') if rand(10) > 4
    w.size.times do |i|
      w[i] = w[i].swapcase if rand(10) > 4
    end
    return w
  end
end

app/helpers/addrs_helper.rb
module AddrsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/ui_presets_helper.rb
module UiPresetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_admin_menu.haml
%nav.navbar.navbar-default.navbar-fixed-top{ role: 'navigation' }
  .navbar-header
    %button.navbar-toggle{ :type => 'button', 'data-toggle' => 'collapse', 'data-target' => '#bs-example-navbar-collapse-1' }
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{ href: root_path }
      =image_tag '/i/bblogo.png', alt: t(:BneiBaruh_logo)
  .collapse.navbar-collapse#bs-example-navbar-collapse-1
    %ul.nav.navbar-nav
      %li= link_to :rooms, rooms_path
      %li= link_to :users, users_path
      %li= link_to :roles, roles_path
      %li= link_to :ui_presets, ui_presets_path

      -if StaticPage.count > 0
        %li.dropdown
          %a.dropdown-toggle{ :href => '#', 'data-toggle' => 'dropdown'}
            = t(:static_pages)
            %b.caret
            %ul.dropdown-menu
              -StaticPage.all.each do |page|
                %li=link_to page.title, static_page_path(page)

    =render partial: 'std_user_menu'

app/views/application/_menu.haml
-if current_user.admin?
  = render partial: 'application/admin_menu'
-else
  = render partial: 'application/user_menu'

app/views/application/_select_language.haml
=select_tag 'set_user_lang', options_for_select([[:ru, :ru], [:he, :he], [:de, :de], [:es,:es], [:fr, :fr], [:it, :it], [:ch, :ch], [:en, :en]]), class: 'form-control', id: 'set_user_lang'

:javascript
  $(document).ready(function(){
    $('#set_user_lang').on('change', function(){
      window.location.href = "#{request.scheme}://#{request.host}:3000/setlanguage/" + $(this).val();
    });
  });

app/views/application/_std_user_menu.haml
%ul.nav.navbar-nav.navbar-right{ style: 'padding-right: 4em;'}
  -if user_signed_in?
    %li= link_to current_user.name, edit_user_registration_path
    %li= link_to t(:sign_out), destroy_user_session_path, :method => :delete
  -else
    %li= link_to t(:sign_in), new_user_session_path
    %li= link_to t(:register), new_user_registration_path

app/views/application/_user_menu.haml
%nav.navbar.navbar-default.navbar-fixed-top{ role: 'navigation' }
  .navbar-header
    %button.navbar-toggle{ :type => 'button', 'data-toggle' => 'collapse', 'data-target' => '#bs-example-navbar-collapse-1' }
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{ href: root_path }
      =image_tag '/i/logo.png', alt: 'логотип БнейБарух'
      %small v0.1
  .collapse.navbar-collapse#bs-example-navbar-collapse-1
    %ul.nav.navbar-nav
      %li= link_to :rooms, rooms_path
      -if StaticPage.count > 0
        %li.dropdown
          %a.dropdown-toggle{ :href => '#', 'data-toggle' => 'dropdown'}
            = t(:static_pages)
            %b.caret
            %ul.dropdown-menu
              -StaticPage.all.each do |page|
                %li
                  =link_to page.title, static_page_path(page)

    =render partial: 'std_user_menu'